services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: inspiration
      POSTGRES_PASSWORD: inspiration
      POSTGRES_DB: inspiration_book
    ports:
      - '5438:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
